### ISSUE TITLE
Dynamic keys should be constructed on the fly with `getData` and `fetchData`

### ISSUE THREAD

**Issue by frozeman** [ERC725Alliance/erc725.js#137]
Dynamic keys (any kind, and future kind as well...)
Should be dynamically constructed when passed into `getData`, `fetchData` or `encode/decode` functions, as follows:

```js
LSP3IssuedAssetsMap: {
      dynamicKeyParts: '0xa3e6F38477D45727F6e6f853Cdb479b0D60c0aC9', // or also ['0xa3e6F38477D45727F6e6f853Cdb479b0D60c0aC9']
      value: '0x6e6f853Cdb479b0D60c0aC9'
}
 ```
 
Example for map key with grouping map with grouping
```js
LSP3IssuedAssetsMapWithGrouping: {
      dynamicKeyParts: ['helloWorld', '0xa3e6F38477D45727F6e6f853Cdb479b0D60c0aC9'], // first group word, second group word
      value: '0xb479b0D60c0aC9'
}
```

if value starts with `0x` do not hash, otherwise hash with `keccak256` before constructing the key.

Also constructed keys need to have `0x` removed in the middle.

**Comment by frozeman** [comment]
If we have this in the schema:
`LSP12Map:<bytes12>:<bytes4>`

```js
{
  'LSP3IssuedAssetsMap': {
      dynamicKeyParts: '0x234567',
      value: '0x23456'
  },
  'LSP3IssuedAssetsMap:MySubGroup': {
      dynamicKeyParts: '0x234567',
      value: '0x23456'
  },
  'LSP12Map': {
      dynamicKeyParts: ['0x234567', '0x2345678'],
      value: '0x23456'
  }
}
```

**Comment by Hugoo** [comment]
```js
erc725.encodeData({
  'LSP3IssuedAssetsMap:<address>': {
    dynamicKeyParts: '0xb8E120e7e5EAe7bfA629Db5CEFfA69C834F74e99',
    value: '0x23456',
});
/**
{
  keys: ['0x83f5e77bfb14241600000000b8E120e7e5EAe7bfA629Db5CEFfA69C834F74e99'],
  values: ['0x23456'],
}
*/
```

Because key is encoded like this:

```
"name": "LSP3IssuedAssetsMap:<address>",
"key": "0x83f5e77bfb14241600000000<address>",
```

Cases:

- [ ] [Mapping](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md#mapping) 
 - "Anything" (word)
- [ ] [Bytes20Mapping](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md#bytes20mapping)
 - `bytes20` or `address`
- [ ] [Bytes20MappingWithGrouping](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md#bytes20mappingwithgrouping)
 - "anything" (word) then `bytes20` or `address`

<https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-2-ERC725YJSONSchema.md#keytype>
