### ISSUE TITLE
Bug in encodeData() with tuples

### ISSUE THREAD

**Issue by m4r-v1n** [ERC725Alliance/erc725.js#393]
v0.23.1

```
ERC725.encodeData([
    {
        keyName: 'LSP4CreatorsMap:<address>',
        dynamicKeyParts: address,
        value: ['0xb3c4928f', 0]
    }
], LSP4DigitalAssetSchema)
```

encodes value to `0xb3c4928f00000000000000000000000000000000000000000000000000000000`
but should encode to `0xb3c4928f00000000000000000000000000000000`
because `LSP4CreatorsMap`'s `valueType` is `(bytes4,uint128)`.

the bug is here:
https://github.com/ERC725Alliance/erc725.js/blob/8a783368f4f3deb2f9810a86cf5424d8d95d2627/src/lib/utils.ts#L211

it treats everything as `bytes*` and hence substrings `"uint128"` to `"28"`...

**Comment by CJ42** [comment]
Thanks for reporting @m4r-v1n 
This seems to have been fixed with #427 . I am double checking the behaviour but that looks good to me.
Also would be good to improve the Typescript typing here.

With this ✅ 

<img width="869" alt="image" src="https://github.com/ERC725Alliance/erc725.js/assets/31145285/560bee1d-b081-4633-bc92-fa12e4d1bcdf">


Over this ❌ 

<img width="671" alt="image" src="https://github.com/ERC725Alliance/erc725.js/assets/31145285/95e9d481-3735-418e-9e9d-bc4dc452a472">
